GET http://localhost:8000/api/status

### Fetch config
GET http://localhost:8000/api/monitors/config

### Create monitor
POST http://localhost:8000/api/monitors
Content-Type: application/json

{
  "name": "A simple check",
  "plugin": "web",
  "enabled": true,
  "frequency": 15,
  "runsOn": [],
  "params": "url: http://example.net"
}

### Delete monitor
DELETE http://localhost:8000/api/monitors/web/blah test check

### Get all monitors
GET http://localhost:8000/api/monitors

### Get a monitor
GET http://localhost:8000/api/monitors/web/blah

### Update monitor
PUT http://localhost:8000/api/monitors/web/A simple check
Content-Type: application/json

{
  "enabled": true,
  "frequency": 20,
  "runsOn": [],
  "params": "url: http://example.net"
}

# =================================================================

### List all plugins
GET http://localhost:8000/api/plugins/

### Get a plugin
GET http://localhost:8000/api/plugins/web
