name: CI Build
on: [push, pull_request]

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: make lint
